dist: xenial
language: node_js
node_js:
  - 10.9
install:
  - npm install
  - docker run --name mongodb -d mongo:3.6
  - docker run -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
script:
  - npm run lint
  - npm test

notifications:
  on_success: change
  on_failure: always
