language: node_js
node_js:
  - 10.9
install:
  - npm install
  - sudo apt-get remove -y docker docker-engine docker.io
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - docker run --name mongodb -d mongo:3.6
  - docker run -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
script:
  - npm run lint
  - npm test

notifications:
  on_success: change
  on_failure: always
